"""empty message

Revision ID: 381a73286a13
Revises: 
Create Date: 2022-01-24 06:56:59.073781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381a73286a13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.String(length=3), nullable=True, comment='星期'),
    sa.Column('is_holiday', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('is_del', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_del', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('calendar')
    # ### end Alembic commands ###
