"""empty message

Revision ID: 58bef7a4f70d
Revises: feb21940cf4d
Create Date: 2022-01-29 06:07:41.644410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58bef7a4f70d'
down_revision = 'feb21940cf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'num_of_guests')
    op.drop_column('orders', 'room_type')
    op.drop_column('orders', 'arrival_datetime')
    op.drop_column('orders', 'booker_phone')
    op.drop_column('orders', 'nights')
    op.drop_column('orders', 'booker_email')
    op.drop_column('orders', 'booker_gender')
    op.drop_column('orders', 'check_in_date')
    op.drop_column('orders', 'booker_name')
    op.drop_column('orders', 'check_out_date')
    op.drop_column('orders', 'room_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('room_quantity', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('check_out_date', sa.DATE(), nullable=False))
    op.add_column('orders', sa.Column('booker_name', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('orders', sa.Column('check_in_date', sa.DATE(), nullable=False))
    op.add_column('orders', sa.Column('booker_gender', mysql.VARCHAR(length=2), server_default=sa.text("'M'"), nullable=True))
    op.add_column('orders', sa.Column('booker_email', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('orders', sa.Column('nights', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('booker_phone', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('orders', sa.Column('arrival_datetime', mysql.DATETIME(), nullable=True))
    op.add_column('orders', sa.Column('room_type', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('orders', sa.Column('num_of_guests', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
