"""empty message

Revision ID: 8610b1ee2750
Revises: d5af514b3c38
Create Date: 2022-01-28 06:42:23.120397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8610b1ee2750'
down_revision = 'd5af514b3c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'note')
    # ### end Alembic commands ###
