"""empty message

Revision ID: 87eb5c472d1b
Revises: 
Create Date: 2022-01-24 12:13:34.962553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87eb5c472d1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.String(length=3), nullable=True, comment='星期'),
    sa.Column('is_holiday', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('orders',
    sa.Column('oid', sa.String(length=64), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('num_of_guests', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('booker_name', sa.String(length=128), nullable=False),
    sa.Column('booker_gender', sa.String(length=2), server_default='M', nullable=True),
    sa.Column('booker_phone', sa.String(length=10), nullable=False),
    sa.Column('booker_email', sa.String(length=128), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=True),
    sa.Column('payment_deadline', sa.Date(), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PENDING', 'PAID', 'CANCEL', 'REFUND', name='orderstatus'), server_default='NEW', nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_user', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('payment_atm',
    sa.Column('pid', sa.String(length=32), nullable=False),
    sa.Column('bank', sa.String(length=128), nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_user', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('room_types',
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('accommodate', sa.Integer(), nullable=True),
    sa.Column('rate_weekday', sa.Integer(), nullable=False),
    sa.Column('rate_holiday', sa.Integer(), nullable=False),
    sa.Column('single_discount', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('is_del', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_del', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rooms',
    sa.Column('room_no', sa.String(length=64), nullable=False),
    sa.Column('room_type', sa.String(length=128), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['room_type'], ['room_types.type'], ),
    sa.PrimaryKeyConstraint('room_no')
    )
    op.create_table('booking',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('room_no', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['calendar.date'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.oid'], ),
    sa.ForeignKeyConstraint(['room_no'], ['rooms.room_no'], ),
    sa.PrimaryKeyConstraint('date', 'room_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('rooms')
    op.drop_table('users')
    op.drop_table('room_types')
    op.drop_table('payment_atm')
    op.drop_table('orders')
    op.drop_table('calendar')
    # ### end Alembic commands ###
