"""empty message

Revision ID: 9e7dcbb19330
Revises: 64ac0c75e612
Create Date: 2022-01-24 23:31:03.478838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e7dcbb19330'
down_revision = '64ac0c75e612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'room_name')
    op.add_column('orders', sa.Column('room_type', sa.String(length=128), nullable=False))
    op.add_column('orders', sa.Column('room_quantity', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.create_foreign_key(None, 'orders', 'room_types', ['room_type'], ['type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'room_quantity')
    op.drop_column('orders', 'room_type')
    op.add_column('booking', sa.Column('room_name', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
