"""empty message

Revision ID: a091d81bd66c
Revises: b6b831668178
Create Date: 2022-01-24 07:47:36.161956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a091d81bd66c'
down_revision = 'b6b831668178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('room_no', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['calendar.date'], ),
    sa.PrimaryKeyConstraint('date', 'room_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
