"""empty message

Revision ID: c64755991cdd
Revises: 58bef7a4f70d
Create Date: 2022-02-09 22:26:12.218284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64755991cdd'
down_revision = '58bef7a4f70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('is_del', sa.Boolean(), server_default=sa.text('0'), nullable=True))
    op.add_column('payment_atm', sa.Column('is_del', sa.Boolean(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_atm', 'is_del')
    op.drop_column('booking', 'is_del')
    # ### end Alembic commands ###
