"""empty message

Revision ID: d5af514b3c38
Revises: 9e7dcbb19330
Create Date: 2022-01-25 18:27:03.738077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5af514b3c38'
down_revision = '9e7dcbb19330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'payment_atm', ['payment_id'], ['pid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###
