"""empty message

Revision ID: feb21940cf4d
Revises: 8610b1ee2750
Create Date: 2022-01-29 05:52:37.533592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'feb21940cf4d'
down_revision = '8610b1ee2750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('num_of_guests', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('room_type', sa.String(length=64), nullable=False),
    sa.Column('room_quantity', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('booker_name', sa.String(length=128), nullable=False),
    sa.Column('booker_gender', sa.String(length=2), server_default='M', nullable=True),
    sa.Column('booker_phone', sa.String(length=10), nullable=False),
    sa.Column('booker_email', sa.String(length=128), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.oid'], ),
    sa.ForeignKeyConstraint(['room_type'], ['room_types.type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_column('orders', 'room_quantity')
    op.drop_column('orders', 'booker_gender')
    op.drop_column('orders', 'booker_name')
    op.drop_column('orders', 'arrival_datetime')
    op.drop_column('orders', 'num_of_guests')
    op.drop_column('orders', 'nights')
    op.drop_column('orders', 'check_out_date')
    op.drop_column('orders', 'booker_email')
    op.drop_column('orders', 'check_in_date')
    op.drop_column('orders', 'booker_phone')
    op.drop_column('orders', 'room_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('room_type', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('orders', sa.Column('booker_phone', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('orders', sa.Column('check_in_date', sa.DATE(), nullable=False))
    op.add_column('orders', sa.Column('booker_email', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('orders', sa.Column('check_out_date', sa.DATE(), nullable=False))
    op.add_column('orders', sa.Column('nights', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('num_of_guests', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('arrival_datetime', mysql.DATETIME(), nullable=True))
    op.add_column('orders', sa.Column('booker_name', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('orders', sa.Column('booker_gender', mysql.VARCHAR(length=2), server_default=sa.text("'M'"), nullable=True))
    op.add_column('orders', sa.Column('room_quantity', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_ibfk_1', 'orders', 'room_types', ['room_type'], ['type'])
    op.drop_table('order_details')
    # ### end Alembic commands ###
